# Generated by Django 4.2.3 on 2025-05-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlasticItem',
        ),
        migrations.DeleteModel(
            name='PlasticRecord',
        ),
    ]
