# Generated by Django 4.2.3 on 2025-05-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlasticItem',
        ),
    ]
