# Generated by Django 4.2.3 on 2025-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triblinbackend', '0006_delete_plasticitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
