# Generated by Django 4.2.3 on 2025-05-24 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticitem',
            name='item_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
