# Generated by Django 4.2.3 on 2025-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0008_alter_plasticitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticitem',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plasticitem',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
