# Generated by Django 4.2.3 on 2025-06-04 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0009_alter_plasticitem_date_alter_plasticitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('program_name', models.CharField(max_length=100)),
                ('program_description', models.TextField(blank=True, null=True)),
                ('program_start_date', models.DateField()),
                ('program_end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='plasticitem',
            name='replace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Programusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triblinbackend.program')),
            ],
        ),
    ]
