# Generated by Django 4.2.3 on 2025-06-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0011_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='username',
            new_name='name',
        ),
    ]
