# Generated by Django 4.2.3 on 2025-06-09 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0012_rename_username_messages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('Blog_title', models.CharField(max_length=100)),
                ('Blog_description', models.CharField(max_length=100)),
                ('Blog_Content', models.TextField(max_length=50000)),
            ],
        ),
    ]
