# Generated by Django 4.2.3 on 2025-06-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0013_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_description',
            field=models.CharField(max_length=1000),
        ),
    ]
