# Generated by Django 4.2.3 on 2025-06-09 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0014_alter_blogs_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triblinbackend.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='location_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plastic_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('plastic_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triblinbackend.location')),
            ],
        ),
        migrations.CreateModel(
            name='Plastic_Item_Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('replaced_with', models.CharField(max_length=100)),
                ('disposed_type', models.CharField(max_length=100)),
                ('plastic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triblinbackend.plastic_item')),
            ],
        ),
    ]
