# Generated by Django 4.2.3 on 2025-06-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0015_authuser_location_location_count_plastic_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.DeleteModel(
            name='location_count',
        ),
        migrations.RemoveField(
            model_name='plastic_item',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='plastic_item_replacement',
            name='plastic_name',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Plastic_Item',
        ),
        migrations.DeleteModel(
            name='Plastic_Item_Replacement',
        ),
    ]
