# Generated by Django 4.2.3 on 2025-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0017_location_location_count_plastic_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location_count',
        ),
    ]
