# Generated by Django 4.2.3 on 2025-06-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0018_delete_location_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triblinbackend.authuser')),
            ],
        ),
    ]
