# Generated by Django 4.2.3 on 2025-06-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0019_location_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plastic_item_replacement',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='plastic_item_replacement',
            name='plastic_name',
        ),
        migrations.RemoveField(
            model_name='plastic_item_replacement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plastic_Item',
        ),
        migrations.DeleteModel(
            name='Plastic_Item_Replacement',
        ),
    ]
