# Generated by Django 4.2.3 on 2025-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0021_plastic_item_plastic_item_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plastic_item',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
