# Generated by Django 4.2.3 on 2025-06-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triblinbackend', '0022_alter_plastic_item_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plastic_Item_Replacement',
        ),
    ]
